spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://52.78.174.166:3306/jejuro
    username: jejuro
    password: jejudo90
  mail:
    host: smtp.gmail.com
    port: 587
    username: {userEmail}
    password: {userPassword}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: true